package com.cybozu.kintone.client;

public class TestConstants {
    public static final String DOMAIN = "https://xxx.cybozu.com";
    public static final String HADOMAIN = "https://xxx.cybozu-dev.com";
    public static final String BASIC_DOMAIN = "https://xxx.cybozu-dev.com";
    public static final String WRONG_DOMAIN = "https://xxx.cybozu";
    public static final String SECURE_DOMAIN = "https://xxx.s.cybozu.com";
    public static final String HASECURE_DOMAIN = "https://xxx.s.cybozu-dev.com";
    public static final String ADMIN_USERNAME = "xxx";
    public static final String ADMIN_PASSWORD = "xxx";
    public static final String BASIC_USERNAME = "xxxx";
    public static final String BASIC_PASSWORD = "xxxx";
    public static final String USERNAME = "xxx";
    public static final String PASSWORD = "xxx";
    public static int SPACE_ID;
    public static int SPACE_APP_ID;
    public static int SPACE_THREAD_ID;
    public static int GUEST_SPACE_ID;
    public static int GUEST_SPACE_APP_ID;
    public static int GUEST_SPACE_THREAD_ID;
    public static int MAX_VALUE;
    public static final String PROXY_HOST = "xxx";
    public static final String PROXY_HOST_HTTP = "xxx";
    public static int PROXY_PORT_HTTP;
    public static int PROXY_PORT;
    public static String API_TOKEN = "xxxxxxxxxxxxxxxxxxxx";
    public static String HAAPI_TOKEN = "xxxxxxxxxxxxxxxxxxxxxxx";
    public static final String PROXY_USERNAME = "xxx";
    public static final String PROXY_PASSWORD = "xxx";
    public static String CLIENT_CERT_PATH = "src/test/resources/certificates/testUser/xxx.pfx";
    public static String HACLIENT_CERT_PATH = "src/test/resources/certificates/testUser/xxx.pfx";
    public static String WRONG_CLIENT_CERT_PATH = "src/test/resources/certificates/testUser/xxx.pfx";
    public static String EXPIRED_CLIENT_CERT_PATH = "src/test/resources/certificates/testUser/xxx.pfx";
    public static String UPLOAD_PATH = "src/test/resources/file/Upload/";
    public static String DOWNLOAD_PATH = "src/test/resources/file/Download/";
    public static String CLIENT_CERT_PASSWORD = "xxx";
    public static String HACLIENT_CERT_PASSWORD = "xxx";
    public static String EXPIRED_CLIENT_CERT_PASSWORD = "xxx";
}
